### ISSUE TITLE
Unable to change port/ip

### ISSUE THREAD

**Issue by danjustice2** [Zaarrg/dh-server#1]
The commands provided in the readme don’t seem to do anything and I can’t find any mention of these settings in the config.

I’m running Fabric on Minecraft 1.20.1

Let me know if you need any other info let me know. I tried to look around a bit in the code, but my Java knowledge is unfortunately next to none 🙂

**Comment by Zaarrg** [comment]
This repo was only a fork to make it work in 1.21 faster. The offical repo got updated shortly after so for any other issue please go to the [official server repo](https://gitlab.com/s809/distant-horizons) and open a [issue](https://gitlab.com/s809/distant-horizons/-/issues) there  or on the distant horizon [discord](https://discord.com/invite/distant-horizons).
