### ISSUE TITLE
LOD disappears after dying in another dimension

### ISSUE THREAD

**Issue by Alpdrucken** [Zaarrg/dh-server#2]
in multiplayer, if i die in the nether/end (probably happens in any dimension), upon respawning in the overworld the LOD doesnt appear and i need to quit and rejoin to make it reappear. doesnt happen in singleplayer and doesnt happen in DH stable https://mclo.gs/Cv7Xel8 doesnt happen if i teleport from one dimension to another without dying.
Tested on a clean installation on 1.20.1

**Comment by Zaarrg** [comment]
This repo was only a fork to make it work in 1.21 faster. The offical repo got updated shortly after so for any other issue please go to the [official server repo](https://gitlab.com/s809/distant-horizons) and open a [issue](https://gitlab.com/s809/distant-horizons/-/issues) there  or on the distant horizon [discord](https://discord.com/invite/distant-horizons).
