### ISSUE TITLE
FullDataSourceRequestMessage and FullDataSourceResponseMessage spam in console

### ISSUE THREAD

**Issue by Alpdrucken** [Zaarrg/dh-server#3]
In the server console i get an undending spam of 

[Netty Epoll Server IO #7/INFO]: Received message: FullDataSourceRequestMessage{futureId=170, levelName=minecraft:overworld, sectionPos=-687194762490, clientTimestamp=null}

and

FullDataSourceResponseMessage{futureId=135, fullDataSource=6*20,-9, dataSourceDto=null}

with varying numbers, and when this happens mobs freeze in place for a few ticks. Ping or tps dont seem to be affected.
example log: https://mclo.gs/a9INgqt
modlist: https://mclo.gs/tzVVdwX

i realize these messages are normal, the problem seems to be that even if i stand in place and the LOD around me is already loaded, the messages just keep going with no apparent end.  I used chunky with dh disabled to generate a bunch of chunks.

**Comment by Zaarrg** [comment]
This repo was only a fork to make it work in 1.21 faster. The offical repo got updated shortly after so for any other issue please go to the [official server repo](https://gitlab.com/s809/distant-horizons) and open a [issue](https://gitlab.com/s809/distant-horizons/-/issues) there  or on the distant horizon [discord](https://discord.com/invite/distant-horizons).
